*** empty log message ***

diff --git a/bartlby.startup.in b/bartlby.startup.in
--- a/bartlby.startup.in
+++ b/bartlby.startup.in
@@ -12,52 +12,6 @@ ulimit -c 1000
 export MALLOC_CHECK_=2
 
 
-function bartlby_status {
-	if [ -f $1 ]; then
-		echo "PID file:                 [exists ]";
-	else
-		echo "PID file:                 [missing]";
-		exit;
-	fi;
-	MYPID=`cat $1`;
-	a=`ps ww --pid $MYPID|wc -l`
-	a=`expr $a \- 1`;
-		echo "Processes:                [$a]";
-	if [ $a != 1 ]; then
-		echo "Bartlby seems not to be running";
-		exit 5;
-	fi;
-	
-	echo "Bartlby seems not to be fine";
-}
-function start_bartlby  {
-	if [ -f $1 ]; then
-		echo "PIDFILE: $1 exists (remove it and rerun start)";
-		exit 3;
-	fi;
-	
-	echo "starting bartlby";
-	$BTL_DIR/${BIN_DIR}bartlby $BTL_DIR/${ETC_DIR}bartlby.cfg
-
-}
-
-function stop_bartlby {
-	echo "stopping bartlby";
-	if [ ! -f $1 ];  then
-		echo "PIDFILE $1 does not exists";
-		exit 4;
-	fi;
-	BART_PID=`cat $1`;
-	kill -USR1 $BART_PID
-	
-}
-
-
-function raiseErr {
-	echo $1;
-	exit $2;
-}
-
 function getConfigValue {
 	if [ ! -f $BTL_DIR/bartlby.cfg ];
 	then
@@ -70,6 +24,116 @@ function getConfigValue {
 
 }
 
+function bartlby_status {
+	if [ -f $1 ]; then
+		echo "PID file:                 [exists ]";
+	else
+		echo "PID file:                 [missing]";
+		exit;
+	fi;
+	OUTP=$($BTL_DIR/bartlby_shmt $BTL_DIR/${ETC_DIR}bartlby.cfg status)
+	if [ $? = 2 ];
+	then
+		echo "Cannot find SHM segment, remove the pid file and starup bartlby again";
+	else
+		echo $OUTP|awk '{print "SHMID: " $1; print "Service # " $2; print "Worker # " $3; print "downtime # " $4; print "running: " $5}';
+		echo "run as $USER";
+	fi;
+	MYPID=$(cat $1);
+	if [ ! -f /proc/$MYPID/cmdline ];
+	then
+		echo ">>>>>>>> Found a pid file and a shm segment";
+		echo ">>>>>>>> but the processs doesnt look to run";
+		echo ">>>>>>>> Remove pidfile and './bartlby.startup remove'";
+	fi;
+	
+}
+
+
+function remove_bartlby {
+	OUTP=$($BTL_DIR/bartlby_shmt $BTL_DIR/${ETC_DIR}bartlby.cfg status)
+	SHMID=$(echo $OUTP|awk '{print $1}');
+	ipcrm shm $SHMID;
+	echo "Removed: $SHMID";
+	rm -f $1;
+}
+
+function start_bartlby  {
+	
+	OUTP=$($BTL_DIR/bartlby_shmt $BTL_DIR/${ETC_DIR}bartlby.cfg status)
+	SEXCODE=$?;
+	
+	if [ -f $1 ]; then
+		if [ $SEXCODE = 2 ];
+		then
+			#SHM is broken or not here so well remove pid file
+			rm $1;
+		else	
+		
+			echo "PIDFILE: $1 exists (remove it and rerun start)";
+			echo "SHM found: $OUTP";
+			exit 3;
+		fi;
+	fi;
+	
+	echo "starting bartlby";
+	if [ $SEXCODE = 1 ];
+	then
+		echo "SHM already existing you should remove it";
+		echo "run ./bartlby.startup remove";
+		exit 2;
+	fi;
+	
+	LOGDIR=`getConfigValue "logfile"|tr -d [:cntrl:]`;
+	RUSER=`getConfigValue "user"|tr -d [:cntrl:]`;
+	#Check if LogPermission is OK
+	
+	if [ "${2}x" = "x" ];
+	then
+		if [ $USER != $RUSER ]; 
+		then
+			su -c "echo 1 >> ${LOGDIR}.$(date +%Y.%m.%d)" - $RUSER
+			EXC=$?;
+			if [ $EXC != 0 ];
+			then
+				raiseErr "either the user '${RUSER}' does not exist or the logfile: ${LOGDIR}.$(date +%Y.%m.%d) does not exist or is not writeable" 5
+			
+			fi;
+		else
+			echo 1 >> ${LOGDIR}.$(date +%Y.%m.%d)
+			EXC=$?;
+			if [ $EXC != 0 ];
+			then
+				raiseErr "either the user '${RUSER}' does not exist or the logfile: ${LOGDIR}.$(date +%Y.%m.%d) does not exist or is not writeable" 5
+			fi;
+				
+		fi;	
+	fi;
+	
+	$BTL_DIR/${BIN_DIR}bartlby $BTL_DIR/${ETC_DIR}bartlby.cfg
+
+}
+
+function stop_bartlby {
+	echo "stopping bartlby";
+	if [ ! -f $1 ];  then
+		if [ "${2}x" = "x" ];
+		then
+			echo "PIDFILE $1 does not exists";
+			exit 4;
+		fi;
+	fi;
+	BART_PID=`cat $1`;
+	kill -USR1 $BART_PID
+	
+}
+
+
+function raiseErr {
+	echo $1;
+	exit $2;
+}
+
 if [ ! -d $BTL_DIR ]; then
 	raiseErr "Dir $BTL_DIR does not exist" 2
 	
@@ -77,45 +141,37 @@ fi;
 
 cd $BTL_DIR;
 PIDDIR=`getConfigValue "pidfile_dir"|tr -d [:cntrl:]`;
-LOGDIR=`getConfigValue "logfile"|tr -d [:cntrl:]`;
-RUSER=`getConfigValue "user"|tr -d [:cntrl:]`;
+
 PIDNAME=$PIDDIR/bartlby.pid
 
 
-#Check if LogPermission is OK
-if [ $USER != $RUSER ]; 
-then
-	su -c "echo 1 >> ${LOGDIR}.$(date +%Y.%m.%d)" - $RUSER
-	EXC=$?;
-	if [ $EXC != 0 ];
-	then
-		raiseErr "either the user '${RUSER}' does not exist or the logfile: ${LOGDIR}.$(date +%Y.%m.%d) does not exist or is not writeable" 5
-	
-	fi;
-else
-	echo 1 >> ${LOGDIR}.$(date +%Y.%m.%d)
-	EXC=$?;
-	if [ $EXC != 0 ];
-	then
-		raiseErr "either the user '${RUSER}' does not exist or the logfile: ${LOGDIR}.$(date +%Y.%m.%d) does not exist or is not writeable" 5
-	fi;
-		
-fi;
+
 
 case $1 in
 	start)
 		
 		start_bartlby $PIDNAME;;
+	startwithout)
+		start_bartlby $PIDNAME no;;
 	stop)
 		
 		stop_bartlby $PIDNAME;;
 	restart)
 		stop_bartlby $PIDNAME;
-		sleep 10;
+		sleep 5;
+		remove_bartlby $PIDNAME;
+		sleep 5;
 		start_bartlby $PIDNAME;;
-		
+	restartwithout)
+		stop_bartlby $PIDNAME no;
+		sleep 5;
+		remove_bartlby $PIDNAME;
+		sleep 5;
+		start_bartlby $PIDNAME no;;	
 	status) 
 		bartlby_status $PIDNAME;;
+	remove)
+		remove_bartlby $PIDNAME;;
 	*)
 		echo "bartlby.startup [stop|start|restart|status]"
 		
