core: configure/ --with-user= core: configure/ install all files and directories with chown $BARTLBY_USER core: lib/mysql [worker|service|server]_by_id returns negative value if not found

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -311,7 +311,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MYSQL_USER MYSQL_PASS MYSQL_HOST MYSQL_DB PLUGIN_DIR CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CPP EGREP INC_MYSQL LIB_MYSQL LD_DL LD_MYSQL AWK SET_MAKE LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MYSQL_USER MYSQL_PASS MYSQL_HOST MYSQL_DB PLUGIN_DIR CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CPP EGREP INC_MYSQL LIB_MYSQL LD_DL BARTLBY_USER AWK SET_MAKE INSTALL_PATH INSTALL_OPTIONS LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -856,6 +856,7 @@ Optional Packages:
   --with-plugin-dir       Where are the plugins located
   --with-mysql-inc=PATH   include path for MySQL headers
   --with-mysql-lib=PATH   library path for MySQL libraries
+  --with-user             Bartlby User
 
 Some influential environment variables:
   CC          C compiler command
@@ -1319,7 +1320,6 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
 
-
 # Check whether --with-mysql-user or --without-mysql-user was given.
 if test "${with_mysql_user+set}" = set; then
   withval="$with_mysql_user"
@@ -1327,6 +1327,8 @@ if test "${with_mysql_user+set}" = set; then
 else
   MYSQL_USER="root"
 fi;
+
+
 
 
 
@@ -1347,6 +1349,7 @@ if test "${with_mysql_host+set}" = set; then
 else
   MYSQL_HOST="localhost"
 fi;
+
 
 
 
@@ -3603,6 +3606,18 @@ fi
 
 
 
+
+# Check whether --with-user or --without-user was given.
+if test "${with_user+set}" = set; then
+  withval="$with_user"
+  BARTLBY_USER="${withval}"
+else
+  BARTLBY_USER="bartlby"
+fi;
+
+INSTALL_OPTIONS="-o $BARTLBY_USER";
+
+
 for ac_prog in gawk mawk nawk awk
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
@@ -4394,6 +4409,55 @@ else
 echo "${ECHO_T}no" >&6
   SET_MAKE="MAKE=${MAKE-make}"
 fi
+
+
+# Extract the first word of "install", so it can be a program name with args.
+set dummy install; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_INSTALL_PATH+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $INSTALL_PATH in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_INSTALL_PATH="$INSTALL_PATH" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_INSTALL_PATH="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  ;;
+esac
+fi
+INSTALL_PATH=$ac_cv_path_INSTALL_PATH
+
+if test -n "$INSTALL_PATH"; then
+  echo "$as_me:$LINENO: result: $INSTALL_PATH" >&5
+echo "${ECHO_T}$INSTALL_PATH" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+if test "x${INSTALL_PATH}" = "x" ; then
+ { { echo "$as_me:$LINENO: error: \"install\" is not found please fix it" >&5
+echo "$as_me: error: \"install\" is not found please fix it" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+
+
 
 
 # Checks for libraries.
@@ -7589,9 +7653,11 @@ s,@EGREP@,$EGREP,;t t
 s,@INC_MYSQL@,$INC_MYSQL,;t t
 s,@LIB_MYSQL@,$LIB_MYSQL,;t t
 s,@LD_DL@,$LD_DL,;t t
-s,@LD_MYSQL@,$LD_MYSQL,;t t
+s,@BARTLBY_USER@,$BARTLBY_USER,;t t
 s,@AWK@,$AWK,;t t
 s,@SET_MAKE@,$SET_MAKE,;t t
+s,@INSTALL_PATH@,$INSTALL_PATH,;t t
+s,@INSTALL_OPTIONS@,$INSTALL_OPTIONS,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
@@ -7870,3 +7936,4 @@ echo "User: $MYSQL_USER";
 echo "Password: $MYSQL_PASS";
 echo "Host: $MYSQL_HOST";
 echo "database: $MYSQL_DB";
+echo "install: $INSTALL_PATH a $install_path";
